name: CI

on:
  push:
    branches:
      - dev
      - dev-sqlite
      - emma
      - emma-eslint-setup
  pull_request:
    branches:
      - dev
      - emma
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests (in-memory DB)
        run: npm run test:mem
      
      - name: Generate coverage report
        run: npm run coverage
      
      - name: Upload coverage to Codecov (optional)
        uses: codecov/codecov-action@v4
        with:
          token: \${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
        continue-on-error: true

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check if app starts
        run: |
          timeout 10s npm start || code=\$?
          if [ \$code -eq 124 ]; then
            echo "App started successfully (timed out as expected)"
            exit 0
          else
            echo "App failed to start"
            exit 1
          fi
